# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Deploy
on: [ push ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    environment:
      name: pypi
      url: https://pypi.org/p/yaclog-ksp
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: '>=3.8'

      - name: Install pypa/build
        run: python -m pip install build --user

      - name: Build a Binary Wheel and Source Tarball
        run: python -m build --sdist --wheel --outdir dist/

      - name: Get Changelog Information
        uses: drewcassidy/yaclog@1.4.2
        id: yaclog-show

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Publish to Github
        run: |
          gh release create ${{ github.ref_name }} \
            --notes-file "${{ steps.yaclog-show.outputs.body_file }}" \
            --title "${{ steps.yaclog-show.outputs.name }}"
          
          gh release upload ${{ github.ref_name }} dist/*
        env:
          GH_TOKEN: ${{ github.token }}